### ISSUE TITLE
Multi clicking a branch speech bubble spams frames at you.

### ISSUE THREAD

**Issue by joseph-abell** [bigjko/cwine#2]
As below.
<img width="1092" alt="screenshot at oct 30 11-46-50" src="https://cloud.githubusercontent.com/assets/1398893/10844964/f1bac91e-7efb-11e5-85d4-4c5fa7756e29.png">

It also looks like you can click any different choice and it will appear

**Comment by bigjko** [comment]
Nice! That's.. a feature!

**Comment by bigjko** [comment]
Fixed!
